import streamlit as st
import time

st.set_page_config(
    page_title="AI Contract Intelligence",
    page_icon="📄",
    layout="wide"
)

st.markdown("""
<style>
.block-container{
    padding-top:1.5rem;
}

.card{
    background:#1f2937;
    padding:18px;
    border-radius:12px;
    border:1px solid #374151;
    margin-bottom:15px;
}

.small{
    color:#9ca3af;
    font-size:14px;
}
</style>
""", unsafe_allow_html=True)

# -------------------------
# Sidebar
# -------------------------

st.title("📄 AI-Powered Contract Intelligence & Risk Scoring")

with st.sidebar:

    st.header("⚙ Navigation")

    st.write("Upload a PDF contract to begin.")

    uploaded_file = st.file_uploader(
        "📂 Upload Contract PDF",
        type=["pdf"]
    )

    analyze = False

    st.divider()

    if uploaded_file:

        st.success("File uploaded successfully")

        st.write(f"**Name:** {uploaded_file.name}")
        st.write(f"**Size:** {uploaded_file.size/(1024*1024):.2f} MB")

        analyze = st.button(
            "🚀 Analyze Contract",
            use_container_width=True
        )

# -------------------------
# Default Values
# -------------------------

documents = 0
risk = "--"
clauses = "--"
status = "Waiting"

summary = "Summary will appear here after backend integration."

risk_text = "Risk score will appear here after AI analysis."

key_clause_text = "Detected clauses will appear here."

risk_details = "Potential risks identified in the contract will appear here."

recommendation = "Recommendations generated by the AI engine will appear here."

entities = "Organizations, people, dates and locations extracted from the contract will appear here."

# -------------------------
# Fake AI Analysis
# -------------------------

if analyze:

    with st.spinner("Analyzing Contract..."):

        time.sleep(2)

    documents = 1
    risk = "23%"
    clauses = 18
    status = "Completed"

    summary = """
Employment agreement between Employer and Employee.

The contract defines compensation,
confidentiality,
termination,
leave policy
and intellectual property ownership.
"""

    risk_text = """
Low Risk

Overall contract risk score: 23%

Most clauses are standard.
"""

    key_clause_text = """
• Confidentiality

• Termination

• Intellectual Property

• Salary

• Non-Compete

• Leave Policy
"""

    risk_details = """
• Missing governing law clause

• No arbitration clause

• Notice period can be improved
"""

    recommendation = """
✔ Add governing law clause

✔ Include arbitration clause

✔ Clarify notice period

✔ Review confidentiality duration
"""

    entities = """
Organization:
ABC Technologies

Employee:
John Smith

Date:
12 June 2026

Location:
Hyderabad
"""

    st.success("✅ Analysis Completed Successfully!")

# -------------------------
# Dashboard
# -------------------------

st.header("📊 AI Contract Analysis Dashboard")

a, b, c, d = st.columns(4)

a.metric("Documents", documents)

b.metric("Risk Score", risk)

c.metric("Clauses", clauses)

d.metric("Status", status)

# -------------------------
# Results
# -------------------------

left, right = st.columns(2)

with left:

    st.markdown(f"""
<div class="card">
<h3>📄 Contract Summary</h3>
<p class="small">{summary}</p>
</div>
""", unsafe_allow_html=True)

with right:

    st.markdown(f"""
<div class="card">
<h3>⚠️ Risk Score</h3>
<p class="small">{risk_text}</p>
</div>
""", unsafe_allow_html=True)

sections = [

("📋 Key Clauses", key_clause_text),

("🚨 Potential Risks", risk_details),

("💡 AI Recommendations", recommendation),

("📝 Named Entities", entities)

]

for title, text in sections:

    st.markdown(f"""
<div class="card">
<h3>{title}</h3>
<p class="small">{text}</p>
</div>
""", unsafe_allow_html=True)

st.caption("🚀 Frontend ready for FastAPI backend integration.")